function l(b,a,c,d,e){b.s.Gb(b.mb,a,c,d,e)}function m(b,a,c,d){b.s.ca?l(b,a,c,d):b.s.Ce()._OnMessageFromDOM({type:"event",component:b.mb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function n(b,a,c){b.s.C(b.mb,a,c)}function t(b,a){for(const [c,d]of a)n(b,c,d)}function u(b){b.Sb||(b.s.pd(b.Wd),b.Sb=!0)}function aa(b){b.Sb&&(b.s.Ne(b.Wd),b.Sb=!1)}window.eb=class{constructor(b,a){this.s=b;this.mb=a;this.Sb=!1;this.Wd=()=>this.Ea()}fd(){}Ea(){}};
window.lf=class{constructor(){this.cd=-1}j(){-1!==this.cd&&(self.clearTimeout(this.cd),this.cd=-1)}};"use strict";class ba{constructor(b){this.Qb=b;this.Mc=!1;this.Uc=!0}}function ca(b,a){const c=a.elementId,d=b.nc(c,a),e=new ba(d);b.Qa.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.Uc=!!a.isVisible;d.addEventListener("focus",()=>{v(b,"elem-focused",c)});d.addEventListener("blur",()=>{v(b,"elem-blurred",c)});b.kb&&document.body.appendChild(d)}
function w(b,a,c){n(b,a,d=>{const e=x(b,d.elementId);return c(e,d)})}function x(b,a){b=b.Qa.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Qb}function v(b,a,c,d){d||(d={});d.elementId=c;l(b,a,d)}
window.kd=class extends self.eb{constructor(b,a){super(b,a);this.Qa=new Map;this.kb=!0;t(this,[["create",c=>ca(this,c)],["destroy",c=>{c=c.elementId;const d=x(this,c);this.md(d);this.kb&&d.parentElement.removeChild(d);this.Qa.delete(c)}],["set-visible",c=>{if(this.kb){var d=this.Qa.get(c.elementId),e=d.Qb;d.Mc?e.style.display=c.isVisible?"":"none":d.Uc=!!c.isVisible}}],["update-position",c=>{if(this.kb){var d=this.Qa.get(c.elementId),e=d.Qb;e.style.left=c.left+"px";e.style.top=c.top+"px";e.style.width=
c.width+"px";e.style.height=c.height+"px";c=c.fontSize;null!==c&&(e.style.fontSize=c+"em");d.Mc||(d.Mc=!0,d.Uc&&(e.style.display=""))}}],["update-state",c=>{const d=x(this,c.elementId);this.Jb(d,c)}],["focus",c=>{const d=x(this,c.elementId);c.focus?d.focus():d.blur()}],["set-css-style",c=>{const d=x(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{x(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{x(this,c.elementId).removeAttribute(c.name)}]]);
w(this,"get-element",c=>c)}nc(){throw Error("required override");}md(){}Jb(){throw Error("required override");}};"use strict";const da=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),y=/android/i.test(navigator.userAgent),ea=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let fa=0;
function ha(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.af?new Promise(c=>{const d="c3_resolve_"+fa;++fa;self[d]=c;a.textContent=b.ef+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let ia=!1,ja=!1;function ka(){if(!ia){try{new Worker("blob://",{get type(){ja=!0}})}catch(b){}ia=!0}return ja}let A=new Audio;
const la={"audio/webm; codecs=opus":!!A.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!A.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!A.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!A.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!A.canPlayType("audio/mp4"),"audio/mpeg":!!A.canPlayType("audio/mpeg")};A=null;async function ma(b){b=await na(b);return(new TextDecoder("utf-8")).decode(b)}
function na(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const oa=[];let B=0;window.RealFile=window.File;const C=[],ra=new Map,sa=new Map;let ta=0;const ua=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ua.push(b)};const va=new Set(["cordova","playable-ad","instant-games"]);let wa=!1;
window.Ca=class b{constructor(a){this.ca=a.gf;this.xa=null;this.ba="";this.$a=a.df;this.Db={};this.Ta=this.va=null;this.Pb=[];this.I=this.ya=null;this.Qc=!1;this.Dd=0;this.rb=null;this.Za=-1;this.Ve=()=>this.Je();this.Ya=[];this.B=a.Xd;this.Tb="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ka()||(this.ca=!1);this.ca&&ea&&(this.ca=!1);if("playable-ad"===this.B||"instant-games"===this.B)this.ca=!1;if("cordova"===this.B&&this.ca)if(y){const c=
/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&90<=parseInt(c[1],10)||(this.ca=!1)}else this.ca=!1;this.Wb=this.sa=null;"html5"!==this.B||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",c=>this.Fe(c));this.C("runtime","create-job-worker",()=>this.Ge());"cordova"===this.B?document.addEventListener("deviceready",
()=>this.sd(a)):this.sd(a)}j(){this.yc();this.xa&&(this.xa=this.xa.onmessage=null);this.va&&(this.va.terminate(),this.va=null);this.Ta&&(this.Ta.j(),this.Ta=null);this.I&&(this.I.parentElement.removeChild(this.I),this.I=null)}re(){return da&&"cordova"===this.B}uc(){const a=navigator.userAgent;return da&&va.has(this.B)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}pe(){return y}tc(){return y&&va.has(this.B)}async sd(a){"macos-wkwebview"===this.B&&this.Oe();if("playable-ad"===this.B){this.sa=
self.c3_base64files;this.Wb={};await this.ye();for(let d=0,e=a.bb.length;d<e;++d){var c=a.bb[d];this.Wb.hasOwnProperty(c)?a.bb[d]={af:!0,ef:this.Wb[c]}:this.sa.hasOwnProperty(c)&&(a.bb[d]=URL.createObjectURL(this.sa[c]))}a.lc=[]}if("nwjs"===this.B&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.pd(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.cf?this.ba=a.cf:(c=location.origin,this.ba=("null"===c?"file:///":c)+location.pathname,c=this.ba.lastIndexOf("/"),-1!==c&&(this.ba=
this.ba.substr(0,c+1)));a.jf&&(this.Db=a.jf);c=new MessageChannel;this.xa=c.port1;this.xa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Ie(d));this.rb=new self.se(this);await xa(this.rb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",
d)}this.ca?await this.Ee(a,c.port2):await this.De(a,c.port2)}Ac(a){a=this.Db.hasOwnProperty(a)?this.Db[a]:a.endsWith("/workermain.js")&&this.Db.hasOwnProperty("workermain.js")?this.Db["workermain.js"]:"playable-ad"===this.B&&this.sa.hasOwnProperty(a)?this.sa[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async oc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.B&&this.Tb)return a=await this.Eb(d.$e?a:this.$a+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),
d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}qa(){return Math.max(window.innerWidth,1)}ja(){return Math.max(window.innerHeight,1)}rd(a){var c=this.ba,d=location.href,e=this.qa(),f=this.ja(),g=window.devicePixelRatio,h=b.hb(),k=a.qf,p=window.cr_previewImageBlobs||this.sa,q=window.cr_previewProjectFileBlobs,E=window.cr_previewProjectFiles,z=window.nf||
"";a=a.Xd;var r=(new URLSearchParams(self.location.search)).has("debug"),F=this.rb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:k,previewImageBlobs:p,previewProjectFileBlobs:q,previewProjectFileSWUrls:E,swClientId:z,exportType:a,isDebug:r,ife:!!self.pf,jobScheduler:{inputPort:F.Pc,outputPort:F.Yc,maxNumWorkers:F.Se},supportedAudioFormats:la,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.$a+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.$a+"opus.wasm.wasm",isFileProtocol:this.Tb,isiOSCordova:this.re(),isiOSWebView:this.uc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Ee(a,c){const d=this.Ac(a.hf);"preview"===this.B?(this.va=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,k)=>{const p=q=>{this.va.removeEventListener("message",p);q.data&&"ok"===q.data.type?h():k()};this.va.addEventListener("message",p);this.va.postMessage({type:"construct-worker-init","import":(new URL(d,
this.ba)).toString()})})):this.va=await this.oc(d,this.ba,{type:"module",name:"Runtime",$e:!0});this.I=document.createElement("canvas");this.I.style.display="none";const e=this.I.transferControlToOffscreen();document.body.appendChild(this.I);window.c3canvas=this.I;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.lc||[],g=a.bb;f=await Promise.all(f.map(h=>this.Na(h)));g=await Promise.all(g.map(h=>this.Na(h)));if("cordova"===this.B)for(let h=0,k=a.kc.length;h<k;++h){const p=
a.kc[h],q=p[0];if(q===a.dd||"scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))p[1]=await this.Na(q)}this.va.postMessage(Object.assign(this.rd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.kc,mainProjectScript:a.dd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...ya(this.rb)]);this.Pb=C.map(h=>new h(this));this.qd();za(this.ya);self.c3_callFunction=(h,k)=>{var p=this.ya;return p.s.od(p.mb,"js-invoke-function",
{name:h,params:k})};"preview"===this.B&&(self.goToLastErrorScript=()=>this.Gb("runtime","go-to-last-error-script"))}async De(a,c){this.I=document.createElement("canvas");this.I.style.display="none";document.body.appendChild(this.I);window.c3canvas=this.I;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Pb=C.map(g=>new g(this));this.qd();var d=a.bb.map(g=>"string"===typeof g?(new URL(g,this.ba)).toString():g);if(Array.isArray(a.lc)){var e=[...a.lc].map(g=>g instanceof Blob?URL.createObjectURL(g):
g);d.unshift(...e)}d=await Promise.all(d.map(g=>this.Na(g)));await Promise.all(d.map(g=>ha(g)));d=self.C3_ProjectScriptsStatus;e=a.dd;const f=a.kc;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.Na(h),await ha(h),"preview"!==this.B||d[g]||this.ud(g,"main script did not run to completion")}catch(k){this.ud(g,k)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.Na(h),await ha(h);"preview"===this.B&&"object"!==typeof self.kf.mf?(this.Lb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.rd(a),{isInWorker:!1,messagePort:c,canvas:this.I,runOnStartupFunctions:ua}),za(this.ya),this.td(),this.Ta=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ta,a))}ud(a,c){this.Lb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}td(){this.Lb()}Lb(){const a=
window.Ye;a&&(a.parentElement.removeChild(a),window.Ye=null)}async Ge(){const a=await Aa(this.rb);return{outputPort:a,transferables:[a]}}Ce(){if(this.ca)throw Error("not available in worker mode");return this.Ta}Gb(a,c,d,e,f){this.xa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}od(a,c,d,e,f){const g=ta++,h=new Promise((k,p)=>{sa.set(g,{resolve:k,reject:p})});this.xa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},
f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.He(a);if("result"===c)this.Ke(a);else if("runtime-ready"===c)this.Le();else if("alert-error"===c)this.Lb(),alert(a.message);else if("creating-runtime"===c)this.td();else throw Error(`unknown message '${c}'`);}He(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=ra.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Kb(f,!1,""+h);return}if(null===
f)return g;g&&g.then?g.then(h=>this.Kb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Kb(f,!1,""+h)}):this.Kb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Kb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.xa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Ke(a){const c=a.responseId,d=a.isOk;a=a.result;const e=sa.get(c);d?e.resolve(a):e.reject(a);sa.delete(c)}C(a,
c,d){let e=ra.get(a);e||(e=new Map,ra.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static La(a){if(C.includes(a))throw Error("DOM handler already added");C.push(a)}qd(){for(const a of this.Pb)if("runtime"===a.mb){this.ya=a;return}throw Error("cannot find runtime DOM handler");}Ie(a){this.Gb("debugger","message",a)}Le(){for(const a of this.Pb)a.fd()}static hb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
wa)}static vd(a){wa=!!a}pd(a){this.Ya.push(a);this.Fc()}Ne(a){a=this.Ya.indexOf(a);if(-1===a)throw Error("invalid callback");this.Ya.splice(a,1);this.Ya.length||this.yc()}Fc(){-1===this.Za&&this.Ya.length&&(this.Za=requestAnimationFrame(this.Ve))}yc(){-1!==this.Za&&(cancelAnimationFrame(this.Za),this.Za=-1)}Je(){this.Za=-1;for(const a of this.Ya)a();this.Fc()}ea(a){this.ya.ea(a)}ia(a){this.ya.ia(a)}Ec(){this.ya.Ec()}Ib(a){this.ya.Ib(a)}qe(){return!!la["audio/webm; codecs=opus"]}async Pe(a){a=await this.od("runtime",
"opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}ue(a){this.Qc=!0;this.Dd=a}oe(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}nd(a){return!this.oe(a)}async Na(a){return"cordova"===this.B&&(a.startsWith("file:")||this.Tb&&this.nd(a))?(a.startsWith(this.ba)&&(a=a.substr(this.ba.length)),a=await this.Eb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Fe(a){const c=a.filename;switch(a.as){case "text":return await this.ne(c);
case "buffer":return await this.Eb(c);default:throw Error("unsupported type");}}jd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async ne(a){a=await this.jd(a);return await ma(a)}zc(){if(oa.length&&!(8<=B)){B++;var a=oa.shift();this.ze(a.filename,a.ff,a.Ze)}}Eb(a){return new Promise((c,d)=>{oa.push({filename:a,ff:e=>{B--;this.zc();c(e)},Ze:e=>{B--;this.zc();d(e)}});this.zc()})}async ze(a,c,d){try{const e=
await this.jd(a),f=await na(e);c(f)}catch(e){d(e)}}Oe(){var a={type:"ready"};if("windows-webview2"===this.B)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.B)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async ye(){const a=[];for(const [c,d]of Object.entries(this.sa))a.push(this.xe(c,d));await Promise.all(a)}async xe(a,c){if("object"===typeof c)this.sa[a]=new Blob([c.str],{type:c.type}),
this.Wb[a]=c.str;else{let d=await this.Be(c);d||(d=this.Ae(c));this.sa[a]=d}}async Be(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}Ae(a){a=this.Me(a);return this.we(a.data,a.bf)}Me(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+
1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{bf:a,data:d}}we(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:c})}};"use strict";const D=self.Ca;
function Ba(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const Da=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),G={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Ea={dispatchUserScriptEvent:!0},Fa={dispatchRuntimeEvent:!0};
function Ga(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Ha(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function I(b){b=URL.createObjectURL(b);try{return await Ha(b)}finally{URL.revokeObjectURL(b)}}
function Ia(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ja(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await I(b);var d=await Ia(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await I(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await I(b)}
function Ka(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const La=new Set(["input","textarea","datalist","select"]),Ma=new Set(["canvas","body","html"]);function J(b){b.target.tagName&&Ma.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Na(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await I(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ja(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Oa=!1;document.addEventListener("pause",()=>Oa=!0);document.addEventListener("resume",()=>Oa=!1);function za(b){b.Cd=!0;b.Vc=b.s.qa();b.sb=b.s.ja()}async function Pa(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Qa(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ra(b){return await self.C3_GetSvgImageSize(b.blob)}function Sa(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Ta(b){self.setTimeout(()=>{b.Bd=!0},1E3);"cordova"===b.s.B?(document.addEventListener("pause",()=>Ua(b,!0)),document.addEventListener("resume",()=>Ua(b,!1))):document.addEventListener("visibilitychange",()=>Ua(b,document.hidden));return{isSuspended:!(!document.hidden&&!Oa)}}
function Va(b){b.xd||(b.xd=!0,window.addEventListener("deviceorientation",a=>{b.$||l(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},G)}),window.addEventListener("deviceorientationabsolute",a=>{b.$||l(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},G)}))}
function Wa(b){b.wd||(b.wd=!0,window.addEventListener("devicemotion",a=>{if(!b.$){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});l(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},G)}}))}async function Xa(b){await Ga(b.url)}
function Ya(b,a){b.Ed=a.message;-1===b.Kc&&(b.Kc=setTimeout(()=>{b.Kc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Ed)},250))}function K(b){if(!b.$){var a=D.hb();a&&"any"!==b.ad&&Za(b);l(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.qa(),innerHeight:b.ja()})}}function $a(b,a){console.warn("[Construct] Fullscreen request failed: ",a);l(b,"fullscreenerror",{isFullscreen:D.hb(),innerWidth:b.qa(),innerHeight:b.ja()})}
function Ua(b,a){a?b.s.yc():b.s.Fc();l(b,"visibilitychange",{hidden:a})}function ab(b,a,c){"Backspace"===c.key&&J(c);if(!b.$){var d=Da.get(c.code)||c.code;m(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},G)}}
function bb(b,a,c,d){b.$||Ba(c)||m(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function db(b){window!==window.top&&window.focus();fb(b.target)&&document.activeElement&&!fb(document.activeElement)&&document.activeElement.blur()}
function L(b,a,c){if(!b.$){var d=0;"mouse"===c.pointerType&&(d=b.xb);m(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},G);"mouse"===c.pointerType&&(d=
"mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),bb(b,d,c,Ea),b.xb=c.buttons)}}
function gb(b,a,c){if(!b.$&&!Ba(c)){var d=b.xb;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");m(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},G);b.xb=c.buttons;bb(b,c.type,c,Ea)}}
function M(b,a,c){if(!b.$)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];m(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.da,pageX:f.pageX,pageY:f.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
G)}}function hb(b,a,c){document.body.style.transform="";b.da=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.da=a))}}function ib(b,a,c,d){const e=b.qa(),f=b.ja();b.ab=-1;e!=a||f!=c?l(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:D.hb()}):10>d&&jb(b,e,f,d+1)}
function jb(b,a,c,d){-1!==b.ab&&clearTimeout(b.ab);b.ab=setTimeout(()=>ib(b,a,c,d),48)}
function Za(b){b=b.ad;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function fb(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
D.La(class extends self.eb{constructor(b){super(b,"runtime");this.Jd=!0;this.Cd=!1;this.ab=-1;this.ad="any";this.wd=this.xd=!1;this.fc=document.createElement("div");this.fc.className="c3-screen-reader-text";this.fc.setAttribute("aria-live","polite");document.body.appendChild(this.fc);this.Ha=null;this.$=!1;this.Ed="";this.Kc=-1;this.Bd=!1;this.Vc=b.qa();this.sb=b.ja();this.da=this.Cb=0;b.C("canvas","update-size",d=>{var e=this.s;e.Qc||(e=e.I,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+
"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.Jd&&(e.style.display="",this.Jd=!1))});b.C("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.C("runtime","load-webfonts",d=>Pa(d));b.C("runtime","raster-svg-image",d=>Qa(d));b.C("runtime","get-svg-image-size",
d=>Ra(d));b.C("runtime","set-target-orientation",d=>{this.ad=d.targetOrientation});b.C("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.C("runtime","post-to-debugger",d=>Sa(d));b.C("runtime","go-to-script",d=>Sa(d));b.C("runtime","before-start-ticking",()=>Ta(this));b.C("runtime","debug-highlight",d=>{if(d.show){this.Ha||(this.Ha=document.createElement("div"),this.Ha.id="inspectOutline",document.body.appendChild(this.Ha));var e=this.Ha;e.style.display="";e.style.left=
d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Ha&&(this.Ha.style.display="none")});b.C("runtime","enable-device-orientation",()=>Va(this));b.C("runtime","enable-device-motion",()=>Wa(this));b.C("runtime","add-stylesheet",d=>Xa(d));b.C("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.C("runtime","alert",d=>{alert(d.message)});
b.C("runtime","screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.fc.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
b.C("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.C("runtime","set-exporting-to-video",d=>{this.$=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.s.I.style.display="";this.s.ue(d.duration)});b.C("runtime","export-to-video-progress",d=>Ya(this,d));b.C("runtime","exported-to-video",d=>{window.Xe({type:"exported-video",
arrayBuffer:d.arrayBuffer,contentType:d.contentType,time:d.time})});b.C("runtime","exported-to-image-sequence",d=>{window.Xe({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||Ka(e)||d.preventDefault()});const c=b.I;window.addEventListener("selectstart",J);window.addEventListener("gesturehold",J);c.addEventListener("selectstart",J);c.addEventListener("gesturehold",
J);window.addEventListener("touchstart",J,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",J,{passive:!1}),c.addEventListener("pointerdown",J)):c.addEventListener("touchstart",J);this.xb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Na,{passive:!1});window.addEventListener("wheel",Na,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.$&&this.Cd){var d=this.qa();var e=this.ja();if(this.s.tc()){if(this.Bd){if(this.Vc===
d&&e<this.sb){this.Cb=this.sb-e;hb(this,this.sb,this.Cb);d=void 0;break a}0<this.Cb&&(this.Cb=0,hb(this,e,this.Cb))}this.Vc=d;this.sb=e}l(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:D.hb()});this.s.uc()&&(-1!==this.ab&&clearTimeout(this.ab),ib(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>K(this));window.addEventListener("webkitfullscreenchange",()=>K(this));window.addEventListener("mozfullscreenchange",()=>
K(this));window.addEventListener("fullscreenerror",d=>$a(this,d));window.addEventListener("webkitfullscreenerror",d=>$a(this,d));window.addEventListener("mozfullscreenerror",d=>$a(this,d));if(b.uc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Ka(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(D.vd(!0),K(this)):"exited-fullscreen"===d?(D.vd(!1),K(this)):console.warn("Unknown wrapper message: ",d)};this.Ua=new Set;this.Yb=new WeakSet;this.wa=!1}fd(){window.addEventListener("focus",()=>{l(this,"window-focus",null,Fa)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}l(this,"window-blur",{parentHasFocus:a},Fa);this.xb=0});window.addEventListener("focusin",a=>{a=a.target;(La.has(a.tagName.toLowerCase())||Ka(a))&&l(this,"keyboard-blur",null,Fa)});window.addEventListener("keydown",a=>ab(this,"keydown",a));window.addEventListener("keyup",a=>ab(this,"keyup",a));window.addEventListener("dblclick",a=>bb(this,"dblclick",a,G));window.addEventListener("wheel",a=>{this.$||l(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.da,pageX:a.pageX,pageY:a.pageY+this.da,
deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},G)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{db(a);L(this,"pointerdown",a)}),this.s.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{L(this,"pointermove",a)}):window.addEventListener("pointermove",a=>L(this,"pointermove",a)),window.addEventListener("pointerup",a=>L(this,"pointerup",a)),window.addEventListener("pointercancel",
a=>L(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{db(a);gb(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>gb(this,"pointermove",a)),window.addEventListener("mouseup",a=>gb(this,"pointerup",a)),window.addEventListener("touchstart",a=>{db(a);M(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>M(this,"pointermove",a)),window.addEventListener("touchend",a=>M(this,"pointerup",a)),window.addEventListener("touchcancel",a=>M(this,"pointercancel",a)));const b=
()=>this.Ec();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.s.pe()&&!this.s.tc()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{hb(this,this.ja(),navigator.virtualKeyboard.boundingRect.height)}))}qa(){return this.s.qa()}ja(){return this.s.ja()}Ec(){var b=
[...this.Ua];this.Ua.clear();if(!this.wa)for(const a of b)(b=a.play())&&b.catch(()=>{this.Yb.has(a)||this.Ua.add(a)})}ea(b){if("function"!==typeof b.play)throw Error("missing play function");this.Yb.delete(b);let a;try{a=b.play()}catch(c){this.Ua.add(b);return}a&&a.catch(()=>{this.Yb.has(b)||this.Ua.add(b)})}ia(b){this.Ua.delete(b);this.Yb.add(b)}Ib(b){this.wa=!!b}});"use strict";
async function xa(b){if(b.Qe)throw Error("already initialised");b.Qe=!0;var a=b.za.Ac(("playable-ad"===b.za.B?b.za.$a:"")+"dispatchworker.js");b.Jc=await b.za.oc(a,b.lb,{name:"DispatchWorker"});a=new MessageChannel;b.Pc=a.port1;b.Jc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Yc=await Aa(b)}function ya(b){return[b.Pc,b.Yc]}
async function Aa(b){const a=b.Kd.length;var c=b.za.Ac(("playable-ad"===b.za.B?b.za.$a:"")+"jobworker.js");c=await b.za.oc(c,b.lb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Jc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Kd.push(c);return e.port1}
self.se=class{constructor(b){this.za=b;this.lb=b.ba;this.lb="preview"===b.B?this.lb+"workers/":this.lb+b.$a;this.Se=Math.min(navigator.hardwareConcurrency||2,16);this.Jc=null;this.Kd=[];this.Yc=this.Pc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Ca({gf:!0,hf:"workermain.js",bb:["scripts/c3runtime.js"],kc:[],dd:"",df:"scripts/",lc:[],Xd:"html5"}));"use strict";
async function kb(b,a){a=a.type;let c=!0;0===a?c=await lb():1===a&&(c=await mb());l(b,"permission-result",{type:a,result:c})}async function lb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function mb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.Ca.La(class extends self.eb{constructor(b){super(b,"touch");n(this,"request-permission",a=>kb(this,a))}});"use strict";
async function nb(b,a){b.Sc=a.isInWorker;a=document.createElement("video");b.hc=!!a.requestVideoFrameCallback&&!b.s.tc();const c=!!self.createImageBitmap;b.Ab=b.Sc||c;return{postImageBitmaps:b.Ab,supportedFormats:{"video/webm":!!a.canPlayType("video/webm"),"video/ogg":!!a.canPlayType("video/ogg"),"video/mp4":!!a.canPlayType("video/mp4")}}}
async function ob(b,a){if(!b.Ic.has(a)){a.c3_rvfcId=a.requestVideoFrameCallback(()=>ob(b,a));try{const c=a.c3_sequenceNumber++,d=await createImageBitmap(a);c>a.c3_lastFrameSequence&&(a.c3_imageBitmap=d,a.c3_lastFrameSequence=c)}catch(c){}}}function N(b,a,c,d){b.Ic.has(a)||v(b,"playback-event",c,{type:d})}
self.Ca.La(class extends self.kd{constructor(b){super(b,"video");this.Ab=this.hc=this.Sc=this.kb=!1;this.Zb=this.We=0;this.Ic=new WeakSet;n(this,"init",a=>nb(this,a));w(this,"play",a=>{this.ea(a)});w(this,"pause",a=>{this.ia(a);a.pause()});w(this,"set-source",(a,c)=>{a.src=c.src;a.load()});w(this,"set-playback-time",(a,c)=>{try{a.currentTime=c.time}catch(d){console.error("[Video] Exception setting playback time: ",d)}});w(this,"set-playback-rate",(a,c)=>{try{a.playbackRate=c.rate}catch(d){console.error("[Video] Exception setting playback rate: ",
d)}});w(this,"set-looping",(a,c)=>{a.loop=c.isLooping});w(this,"set-muted",(a,c)=>{a.muted=c.isMuted});w(this,"set-volume",(a,c)=>{a.volume=c.volume});self.C3Video_GetElement=a=>x(this,a)}ea(b){this.s.ea(b);this.Ab&&this.hc&&-1===b.c3_rvfcId&&(b.c3_rvfcId=b.requestVideoFrameCallback(()=>ob(this,b)))}ia(b){this.s.ia(b);this.Ab&&this.hc&&-1!==b.c3_rvfcId&&(b.cancelVideoFrameCallback(b.c3_rvfcId),b.c3_rvfcId=-1)}nc(b,a){const c=document.createElement("video");c.crossOrigin="anonymous";c.playsInline=
!0;c.c3_imageBitmap=null;c.c3_rvfcId=-1;c.c3_sequenceNumber=0;c.c3_lastFrameSequence=-1;c.addEventListener("canplay",()=>N(this,c,b,0));c.addEventListener("canplaythrough",()=>N(this,c,b,1));c.addEventListener("ended",()=>N(this,c,b,2));c.addEventListener("error",()=>N(this,c,b,3));c.addEventListener("loadstart",()=>N(this,c,b,4));c.addEventListener("playing",()=>N(this,c,b,5));c.addEventListener("pause",()=>N(this,c,b,6));c.addEventListener("stalled",()=>N(this,c,b,7));const d=a.autoplay;0===d?(c.autoplay=
!1,c.preload="none"):1===d?(c.autoplay=!1,c.preload="auto"):c.autoplay=!0;a.src&&(c.src=a.src);2===d&&this.ea(c);this.Zb++;u(this);return c}Jb(){}md(b){this.ia(b);b&&!b.paused&&!b.ended&&0<b.currentTime&&b.pause();b.src="";this.Zb=Math.max(this.Zb-1,0);0===this.Zb&&aa(this);this.Ic.add(b)}Ea(){const b={},a={sequenceNumber:this.We++,videoData:b},c=[],d=[];for(const [e,f]of this.Qa.entries()){const g=f.Qb,h={currentTime:g.currentTime,playbackRate:g.playbackRate,duration:g.duration,videoWidth:g.videoWidth,
videoHeight:g.videoHeight};if(this.Ab)if(this.hc){const k=g.c3_imageBitmap;g.c3_imageBitmap=null;(h.imageBitmap=k)&&c.push(k)}else d.push(createImageBitmap(g).then(k=>{h.imageBitmap=k;c.push(k)}).catch(()=>{h.imageBitmap=null}));b[e.toString()]=h}Promise.all(d).then(()=>{this.Sc?l(this,"state",a,!1,c):m(this,"state",a)})}});"use strict";function O(b){b.stopPropagation()}
self.Ca.La(class extends self.kd{constructor(b){super(b,"sliderbar")}nc(b,a){const c=document.createElement("input");c.type="range";c.style.position="absolute";c.style.userSelect="none";c.style.webkitUserSelect="none";c.addEventListener("pointerdown",O);c.addEventListener("pointermove",O);c.addEventListener("pointerrawupdate",O);c.addEventListener("pointerup",O);c.addEventListener("mousedown",O);c.addEventListener("mouseup",O);c.addEventListener("keydown",O);c.addEventListener("keyup",O);c.addEventListener("click",
()=>{var d;d||(d={});d.elementId=b;m(this,"click",d)});c.addEventListener("change",()=>v(this,"change",b,{value:parseFloat(c.value)}));c.addEventListener("input",()=>v(this,"input",b,{value:parseFloat(c.value)}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.Jb(c,a);return c}Jb(b,a){b.max=a.max;b.min=a.min;b.step=a.step;b.value=a.value;b.disabled=!a.isEnabled;b.title=a.title}});"use strict";const pb=180/Math.PI;
async function qb(b,a){if(a.isiOSCordova||a.isSafari)b.bc=!0;b.bd=a.timeScaleMode;b.Pd=["equalpower","HRTF","soundfield"][a.panningModel];b.Ad=["linear","inverse","exponential"][a.distanceModel];b.Qd=a.refDistance;b.Od=a.maxDistance;b.Sd=a.rolloffFactor;if(b.s.Qc)b.bc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.s.Dd)});else{var c={latencyHint:a.latencyHint};b.Vd||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");rb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&rb(b);l(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Pa=b.g.createGain();b.Pa.connect(b.g.destination);c=a.listenerPos;b.aa[0]=c[0];b.aa[1]=c[1];b.aa[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.fa);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
P(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function sb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,p=a.pos,q=a.panning,E=a.stereoPan;let z=a.off;0<z&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),z=z-a.performanceTime/1E3+a.contextTime):z=z-performance.now()/1E3+b.g.currentTime);b.Ld=g.slice(0);tb(b,g);try{b.R=await ub(b,c,d,e,g,f);if(q){Q(b.R,!0);var r=b.R,F=q.innerAngle,pa=q.outerAngle,qa=q.outerGain;if(r.qb){vb(r,q.x,q.y,q.z,q.angle);var H=self.cb.ve;r.ta[0]!==H(F)&&
(r.ta[0]=H(F),r.F.coneInnerAngle=H(F));r.ta[1]!==H(pa)&&(r.ta[1]=H(pa),r.F.coneOuterAngle=H(pa));r.ta[2]!==qa&&(r.ta[2]=qa,r.F.coneOuterGain=qa)}q.hasOwnProperty("uid")&&(b.R.ra=q.uid)}else"number"===typeof E&&0!==E?(R(b.R,!0),wb(b.R,E)):(Q(b.R,!1),R(b.R,!1));b.R.Play(h,k,p,z)}catch(Ib){console.error("[Construct] Audio: error starting playback: ",Ib);return}finally{c=g.join(" ");d=b.zb.get(c);if(!d)throw Error("expected pending tag");d.ed--;0===d.ed&&(d.resolve(),b.zb.delete(c))}u(b)}
async function xb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await yb(b,c);for(const h of S(b,c))if(!h.Sa){c=h.G.gain;c.cancelScheduledValues(0);var f=h.u.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Ka=d;h.Ra=g;h.Ud=a}T(b)}async function zb(b,a){const c=a.tags;a=a.rate;await yb(b,c);for(const d of S(b,c))d.na!==a&&(d.na=a,d.Fa())}async function Ab(b,a){const c=a.tags;a=a.pos;await yb(b,c);for(const d of S(b,c))d.vc(a)}
async function Bb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await ub(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function Cb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.la.indexOf(a),-1!==a&&b.la.splice(a,1)}
async function Db(b,a){const c=a.type;var d=a.tags;const e=a.params;let f;if("convolution"===c)try{f=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.ce(b,...e);else if("delay"===c)d=new self.ae(b,...e);else if("convolution"===c){var g=d=new self.$d(b,f.ka,...e),h=a.bufferType;g.yd=a.bufferOriginalUrl;g.zd=h}else if("flanger"===c)d=new self.de(b,...e);else if("phaser"===
c)d=new self.fe(b,...e);else if("gain"===c)d=new self.ee(b,...e);else if("stereopan"===c)d=new self.he(b,...e);else if("tremolo"===c)d=new self.ie(b,...e);else if("ringmod"===c)d=new self.ge(b,...e);else if("distortion"===c)d=new self.be(b,...e);else if("compressor"===c)d=new self.Zd(b,...e);else if("analyser"===c)d=new self.Yd(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let p=g.ma.get(h);p||(p=[],g.ma.set(h,p));d.Id=p.length;d.$c=h;p.push(d);Eb(g,h)}Fb(b)}
async function Gb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Ba()&&1===c||!e.Ba()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.ma.values())for(const g of f)g.j();b.ma.clear();b.ic=a.timeScale;b.Lc=a.gameTime;d=a.listenerPos;b.aa[0]=d[0];b.aa[1]=d[1];b.aa[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.fa[e]=d[e];b.g.listener.setOrientation(...b.fa)}b.wa=a.isSilent;b.s.Ib(b.wa);b.Xb=a.masterVolume;b.Pa.gain.value=
b.Xb;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>Db(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>Hb(b,f,c)));T(b)}
async function Jb(b,a){try{const c=b.g.suspend(a.time);b.Hd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.s.Gb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Kb(d)),b.Hd=!0);await c}catch(c){Kb(c)}}
function rb(b){b.Rb||(b.Oc=!1,window.addEventListener("pointerup",b.Aa,!0),window.addEventListener("touchend",b.Aa,!0),window.addEventListener("click",b.Aa,!0),window.addEventListener("keydown",b.Aa,!0),b.Rb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.la)if(g.gb()===c)return await Lb(g),g;if(f)return null;if(e&&(b.bc||b.Gd)){f=0;for(let h=0,k=b.la.length;h<k;++h)g=b.la[h],b.la[f]=g,g.Ba()?g.j():++f;b.la.length=f}f="audio/webm; codecs=opus"===d&&!b.Vd;e&&f&&(b.Gd=!0);c=!e||b.bc||f?new self.le(b,a,c,d,e,f):new self.je(b,a,c,d,e);b.la.push(c);await Lb(c);b.Nd.has(a)||(l(b,"buffer-metadata",{originalUrl:a,duration:c.ha()}),b.Nd.add(a));return c}
function Mb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Nb(b,a){return(a=b.ma.get(a.toLowerCase()))?a[0].N():b.pa()}function Eb(b,a){a=a.toLowerCase();let c=b.pa();var d=b.ma.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.pa()):e.U(d[f+1].N())}}for(const f of Ob(b,a))d=c,e=f.ga||f.F||f.G,e.disconnect(),e.connect(d);b.Ia&&b.Wc===a&&(b.Ia.disconnect(),b.Ia.connect(c))}
function*Ob(b,a){if(a)for(const c of b.H)Mb(0<c.oa.length?c.oa[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Pb(b,a,c){return c?b.s.Pe(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Qb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*S(b,a){if(0<a.length)for(const d of b.H){a:{b=d.oa;var c=a;for(const e of c){c=!1;for(const f of b)if(Mb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function ub(b,a,c,d,e,f){for(const g of b.H)if(g.gb()===c&&(g.mc()||f))return g.oa=e,g;a=await P(b,a,c,d,f);e="html5"===a.Gc?new self.ke(a.u,a,e):new self.me(a.u,a,e);b.H.push(e);return e}
function tb(b,a){a=a.join(" ");let c=b.zb.get(a);if(!c){let d=null;c={ed:0,promise:new Promise(e=>d=e),resolve:d};b.zb.set(a,c)}c.ed++}function yb(b,a){return(b=b.zb.get((0===a.length?b.Ld:a).join(" ")))?b.promise:Promise.resolve()}function T(b){if(0<b.Oa.size)u(b);else for(const a of b.H)if(!a.J&&!a.O()){u(b);break}}function Rb(b,a,c,d){l(b,"trigger",{type:a,tags:c,aiid:d})}function Fb(b){b.Rc||(b.Rc=!0,Promise.resolve().then(()=>Sb(b)))}
function Sb(b){const a={};for(const [c,d]of b.ma)a[c]=d.map(e=>e.fb());l(b,"fxstate",{fxstate:a});b.Rc=!1}
async function Hb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,p=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await ub(b,d,e,f,h,g)}catch(E){console.error("[Construct] Audio: error loading audio state: ",E);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.Wa[0]=f[0],b.Wa[1]=f[1],b.Wa[2]=f[2],f=d.orient,b.Va[0]=f[0],b.Va[1]=f[1],b.Va[2]=f[2],e.setPosition(...b.Wa),e.setOrientation(...b.Va),b.ta[0]=d.cia,b.ta[1]=d.coa,b.ta[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.ra=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),wb(b,d));c.Play(k,p,q,0);a.isPlaying||c.ib();c.Cc(a)}}}function Kb(b){console.error("[Audio] Offline rendering error: ",b)}
self.cb=class extends self.eb{constructor(b){super(b,"audio");this.Pa=this.g=null;this.Rb=this.Oc=!1;this.Aa=()=>{if(!this.Oc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Rb&&(this.Oc=!0,window.removeEventListener("pointerup",this.Aa,!0),window.removeEventListener("touchend",this.Aa,!0),window.removeEventListener("click",this.Aa,!0),window.removeEventListener("keydown",
this.Aa,!0),this.Rb=!1)}};this.la=[];this.H=[];this.R=null;this.Ld=[];this.Nd=new Set;this.Md=-1;this.zb=new Map;this.Xb=1;this.wa=!1;this.bd=0;this.ic=1;this.Lc=0;this.Pd="HRTF";this.Ad="inverse";this.Qd=600;this.Od=1E4;this.Sd=1;this.aa=[0,0,0];this.fa=[0,0,-1,0,1,0];this.Gd=this.bc=!1;this.Vd=this.s.qe();this.ma=new Map;this.Oa=new Set;this.Hd=this.Rc=!1;this.Wc="";this.Ia=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ia&&this.Ia.disconnect();this.Wc=c.toLowerCase();this.Ia=this.g.createMediaStreamSource(a);
this.Ia.connect(Nb(this,this.Wc))};this.Ob=null;self.C3Audio_GetOutputStream=()=>{this.Ob||(this.Ob=this.g.createMediaStreamDestination(),this.Pa.connect(this.Ob));return this.Ob.stream};self.C3Audio_DOMInterface=this;t(this,[["create-audio-context",a=>qb(this,a)],["play",a=>sb(this,a)],["stop",a=>{a=a.tags;for(const c of S(this,a))c.Da()}],["stop-all",()=>{for(const a of this.H)a.Da()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of S(this,c))a?d.ib():d.Hb();T(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of S(this,c))U(d,a)}],["fade-volume",a=>xb(this,a)],["set-master-volume",a=>{this.Xb=a.vol;this.Pa.gain.value=this.Xb}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of S(this,c))Tb(d,a)}],["set-silent",a=>{this.wa=a.isSilent;this.s.Ib(this.wa);for(const c of this.H)c.Mb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of S(this,c))d.wc(a)}],["set-playback-rate",a=>zb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of S(this,
c))R(d,!0),wb(d,a)}],["seek",a=>Ab(this,a)],["preload",a=>Bb(this,a)],["unload",a=>Cb(this,a)],["unload-all",()=>{for(const a of this.la)a.j();this.la.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.xc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>Db(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ma.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);Fb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ma.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.ma.delete(a);Eb(this,a)}}],["tick",a=>{this.ic=a.timeScale;this.Lc=a.gameTime;this.Md=a.tickCount;if(0!==this.bd)for(var c of this.H)c.Fa();!(c=a.listenerPos)||this.aa[0]===c[0]&&this.aa[1]===c[1]&&this.aa[2]===c[2]||(this.aa[0]=c[0],this.aa[1]=c[1],this.aa[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.fa[0]!==
c[0]||this.fa[1]!==c[1]||this.fa[2]!==c[2]||this.fa[3]!==c[3]||this.fa[4]!==c[4]||this.fa[5]!==c[5])){for(let d=0;6>d;++d)this.fa[d]=c[d];this.g.listener.setOrientation(...this.fa)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.ra===a&&vb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>Gb(this,a)],["offline-render-audio",a=>Jb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}W(){return this.g}pa(){return this.Pa}Fb(){return this.wa}ea(b){this.s.ea(b)}ia(b){this.s.ia(b)}Ea(){for(var b of this.Oa)b.Ea();
b=this.g.currentTime;for(var a of this.H)a.Ea(b);a=this.H.filter(c=>!c.J&&!c.O()).map(c=>c.fb());l(this,"state",{tickCount:this.Md,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Oa].map(c=>({tag:c.$c,index:c.Id,peak:c.Xa,rms:c.Rd,binCount:c.l.frequencyBinCount,freqBins:c.Fd}))});0===a.length&&0===this.Oa.size&&aa(this)}static ve(b){return b*pb}static ld(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static te(b){return Math.log(Math.max(Math.min(b,1),0))/Math.log(10)*
20}};self.Ca.La(self.cb);"use strict";function Lb(b){b.Vb||(b.Vb=b.Bc());return b.Vb}self.gd=class{constructor(b,a,c,d,e){this.u=b;this.Ue=a;this.Ja=c;this.T=d;this.Re=e;this.Gc="";this.Vb=null}j(){this.Vb=this.u=null}Bc(){}W(){return this.u.W()}qc(){return this.Ue}gb(){return this.Ja}pc(){return this.T}Ba(){return this.Re}ha(){}};"use strict";
self.je=class extends self.gd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Gc="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.tb=this.ub=null;this.M.addEventListener("canplaythrough",()=>!0);this.yb=this.W().createGain();this.wb=null;this.M.addEventListener("canplay",()=>{this.ub&&(this.ub(),this.tb=this.ub=null);!this.wb&&this.M&&(this.wb=this.W().createMediaElementSource(this.M),this.wb.connect(this.yb))});this.onended=null;this.M.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.M.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ja}' error: `,f);this.tb&&(this.tb(f),this.tb=this.ub=null)})}j(){Qb(this.u,this);this.yb.disconnect();this.yb=null;this.wb.disconnect();this.wb=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.j()}Bc(){return new Promise((b,a)=>{this.ub=b;this.tb=a;this.M.src=this.Ja})}V(){return this.M}ha(){return this.M.duration}};"use strict";
async function Ub(b){if(b.Ga)return b.Ga;var a=b.u.s;if("cordova"===a.B&&a.nd(b.Ja)&&a.Tb)b.Ga=await a.Eb(b.Ja);else{a=await fetch(b.Ja);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ga=await a.arrayBuffer()}}async function Vb(b){if(b.ka)return b.ka;b.ka=await Pb(b.u,b.Ga,b.Te);b.Ga=null}
self.le=class extends self.gd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Gc="webaudio";this.ka=this.Ga=null;this.Te=!!f}j(){Qb(this.u,this);this.ka=this.Ga=null;super.j()}async Bc(){try{await Ub(this),await Vb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ja}': `,b)}}ha(){return this.ka?this.ka.duration:0}};"use strict";let Wb=0;
function Q(b,a){a=!!a;b.qb!==a&&(b.qb=a,b.qb?(R(b,!1),b.F||(b.F=b.W().createPanner(),b.F.panningModel=b.u.Pd,b.F.distanceModel=b.u.Ad,b.F.refDistance=b.u.Qd,b.F.maxDistance=b.u.Od,b.F.rolloffFactor=b.u.Sd),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.pa())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.pa())))}
function R(b,a){a=!!a;b.Ub!==a&&(b.Ub=a,b.Ub?(Q(b,!1),b.ga=b.W().createStereoPanner(),b.G.disconnect(),b.G.connect(b.ga),b.ga.connect(b.pa())):(b.ga.disconnect(),b.ga=null,b.G.disconnect(),b.G.connect(b.pa())))}function wb(b,a){b.Ub&&b.Zc!==a&&(b.ga.pan.value=a,b.Zc=a)}function U(b,a){b.Ka=a;b.G.gain.cancelScheduledValues(0);b.Ra=-1;b.G.gain.value=b.rc()}function Tb(b,a){a=!!a;b.Sa!==a&&(b.Sa=a,b.Mb())}
function vb(b,a,c,d,e){if(b.qb){var f=b.Wa,g=b.Va,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function V(b){return b.Tc?b.u.Lc:performance.now()/1E3}
self.hd=class{constructor(b,a,c){this.u=b;this.P=a;this.oa=c;this.Nb=Wb++;this.G=this.W().createGain();this.G.connect(this.pa());this.F=null;this.qb=!1;this.Wa=[0,0,0];this.Va=[0,0,0];this.ta=[0,0,0];this.ga=null;this.Ub=!1;this.Zc=0;this.J=!0;this.Y=this.ua=this.K=!1;this.Ka=1;this.Sa=!1;this.na=1;b=this.u.bd;this.Tc=1===b&&!this.Ba()||2===b;this.Ra=this.ra=-1;this.Ud=!1}j(){this.P=this.u=null;this.F&&(this.F.disconnect(),this.F=null);this.ga&&(this.ga.disconnect(),this.ga=null);this.G.disconnect();
this.G=null}W(){return this.u.W()}pa(){return Nb(this.u,0<this.oa.length?this.oa[0]:"")}qc(){return this.P.qc()}gb(){return this.P.gb()}pc(){return this.P.pc()}Ba(){return this.P.Ba()}O(){}mc(){}IsPlaying(){return!this.J&&!this.K&&!this.O()}Ma(){}ha(){return this.P.ha()}Play(){}Da(){}ib(){}Hb(){}Ea(b){-1!==this.Ra&&b>=this.Ra&&(this.Ra=-1,this.Ud&&this.Da(),Rb(this.u,"fade-ended",this.oa,this.Nb))}rc(){const b=this.Ka;return isFinite(b)?b:0}Fb(){return this.u.Fb()}Mb(){}wc(){}Fa(){}vc(){}xc(){}sc(){}fb(){var b=
this.Nb,a=this.oa,c=this.ha(),d=-1===this.Ra?this.Ka:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Wa,orient:this.Va,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.ra}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ma(),playbackRate:this.na,uid:this.ra,bufferOriginalUrl:this.qc(),bufferUrl:"",bufferType:this.pc(),isMusic:this.Ba(),isLooping:this.Y,isMuted:this.Sa,resumePosition:this.sc(),pan:f,stereoPan:this.ga?
this.Zc:null}}Cc(b){var a=b.playbackRate;this.na!==a&&(this.na=a,this.Fa());Tb(this,b.isMuted)}};"use strict";
self.ke=class extends self.hd{constructor(b,a,c){super(b,a,c);this.P.yb.connect(this.G);this.P.onended=()=>this.Dc()}j(){this.Da();this.P.yb.disconnect();super.j()}V(){return this.P.V()}Dc(){this.J=!0;this.ra=-1;Rb(this.u,"ended",this.oa,this.Nb)}O(){return this.V().ended}mc(){return this.J?!0:this.O()}Ma(){let b=this.V().currentTime;this.Y||(b=Math.min(b,this.ha()));return b}Play(b,a,c){const d=this.V();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.gb()}' to position '${c}': `,e)}this.u.ea(d);this.K=this.J=!1;this.Y=b;this.na=1}Da(){const b=this.V();b.paused||b.pause();this.u.ia(b);this.J=!0;this.K=!1;this.ra=-1}ib(){if(!(this.K||this.J||this.O())){var b=this.V();b.paused||b.pause();this.u.ia(b);this.K=!0}}Hb(){!this.K||this.J||this.O()||(this.u.ea(this.V()),this.K=!1)}Mb(){this.V().muted=this.Sa||this.Fb()}wc(b){b=!!b;this.Y!==b&&(this.Y=
b,this.V().loop=b)}Fa(){let b=this.na;this.Tc&&(b*=this.u.ic);try{this.V().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}vc(b){if(!this.J&&!this.O())try{this.V().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}sc(){return this.Ma()}xc(b){b?this.IsPlaying()?(this.V().pause(),this.ua=!0):this.ua=!1:this.ua&&(this.u.ea(this.V()),this.ua=!1)}};"use strict";
function W(b){b.o&&(b.o.onended=null,b.o.disconnect(),b.o.buffer=null);b.o=null;b.jb=null}
self.me=class extends self.hd{constructor(b,a,c){super(b,a,c);this.o=null;this.$b=d=>this.Dc(d);this.Nc=!0;this.jb=null;this.S=this.ac=this.cc=0;this.Xc=1}j(){this.Da();W(this);this.$b=null;super.j()}Dc(b){this.K||this.ua||b.target!==this.jb||(this.J=this.Nc=!0,this.ra=-1,W(this),Rb(this.u,"ended",this.oa,this.Nb))}O(){return!this.J&&this.o&&this.o.loop||this.K?!1:this.Nc}mc(){return!this.o||this.J?!0:this.O()}Ma(){let b;b=this.K?this.S:this.ac+(V(this)-this.cc)*this.na;this.Y||(b=Math.min(b,this.ha()));
return b}Play(b,a,c,d){this.Xc=1;U(this,a);W(this);this.o=this.W().createBufferSource();this.o.buffer=this.P.ka;this.o.connect(this.G);this.jb=this.o;this.o.onended=this.$b;this.o.loop=b;this.o.start(d,c);this.K=this.J=this.Nc=!1;this.Y=b;this.na=1;this.cc=V(this);this.ac=c}Da(){if(this.o)try{this.o.stop(0)}catch(b){}this.J=!0;this.K=!1;this.ra=-1}ib(){this.K||this.J||this.O()||(this.S=this.Ma(),this.Y&&(this.S%=this.ha()),this.K=!0,this.o.stop(0))}Hb(){!this.K||this.J||this.O()||(W(this),this.o=
this.W().createBufferSource(),this.o.buffer=this.P.ka,this.o.connect(this.G),this.jb=this.o,this.o.onended=this.$b,this.o.loop=this.Y,U(this,this.Ka),this.Fa(),this.o.start(0,this.S),this.cc=V(this),this.ac=this.S,this.K=!1)}rc(){return super.rc()*this.Xc}Mb(){this.Xc=this.Sa||this.Fb()?0:1;U(this,this.Ka)}wc(b){b=!!b;this.Y!==b&&(this.Y=b,this.o&&(this.o.loop=b))}Fa(){let b=this.na;this.Tc&&(b*=this.u.ic);this.o&&(this.o.playbackRate.value=b)}vc(b){this.J||this.O()||(this.K?this.S=b:(this.ib(),this.S=
b,this.Hb()))}sc(){return this.S}xc(b){b?this.IsPlaying()?(this.ua=!0,this.S=this.Ma(),this.Y&&(this.S%=this.ha()),this.o.stop(0)):this.ua=!1:this.ua&&(W(this),this.o=this.W().createBufferSource(),this.o.buffer=this.P.ka,this.o.connect(this.G),this.jb=this.o,this.o.onended=this.$b,this.o.loop=this.Y,U(this,this.Ka),this.Fa(),this.o.start(0,this.S),this.cc=V(this),this.ac=this.S,this.ua=!1)}Cc(b){super.Cc(b);this.S=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.u=b;this.g=b.W();this.Id=-1;this.T=this.$c="";this.m=null}j(){this.g=null}N(){}U(){}fb(){return{type:this.T,tag:this.$c,params:this.m}}}
self.ce=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.m=[a,c,d,e,f,g];this.v=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i)}j(){this.v.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[2]=a;Y(this,this.D.detune,a,c,d);break;case 3:this.m[3]=a;Y(this,this.D.Q,a,c,d);break;case 4:this.m[4]=a,Y(this,this.D.gain,a,c,d)}}};
self.ae=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.m=[a,c,d];this.v=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.vb=X(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.ob=X(this);this.ob.gain.value=c;this.v.connect(this.vb);this.v.connect(this.h);this.vb.connect(this.i);this.vb.connect(this.X);this.X.connect(this.ob);this.ob.connect(this.vb)}j(){this.v.disconnect();this.i.disconnect();this.h.disconnect();this.vb.disconnect();
this.X.disconnect();this.ob.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){const e=self.cb.ld;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);Y(this,this.ob.gain,e(a),c,d);break;case 5:this.m[0]=a,Y(this,this.X.delayTime,a,c,d)}}};
self.$d=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.m=[c,d];this.zd=this.yd="";this.v=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.nb=this.g.createConvolver();this.nb.normalize=c;this.nb.buffer=a;this.v.connect(this.nb);this.v.connect(this.h);this.nb.connect(this.i)}j(){this.v.disconnect();this.nb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}fb(){const b=super.fb();b.bufferOriginalUrl=this.yd;b.bufferUrl="";b.bufferType=this.zd;return b}};
self.de=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.m=[a,c,d,e,f];this.v=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.pb=X(this);this.pb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.A=this.g.createOscillator();this.A.frequency.value=d;this.L=X(this);this.L.gain.value=c;this.v.connect(this.X);this.v.connect(this.h);this.X.connect(this.i);this.X.connect(this.pb);this.pb.connect(this.X);this.A.connect(this.L);
this.L.connect(this.X.delayTime);this.A.start(0)}j(){this.A.stop(0);this.v.disconnect();this.X.disconnect();this.A.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();this.pb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;Y(this,this.L.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;Y(this,this.A.frequency,a,c,d);break;case 8:this.m[3]=a/100,Y(this,this.pb.gain,a/100,c,d)}}};
self.fe=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.m=[a,c,d,e,f,g];this.v=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.A=this.g.createOscillator();this.A.frequency.value=f;this.L=X(this);this.L.gain.value=e;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i);this.A.connect(this.L);this.L.connect(this.D.frequency);
this.A.start(0)}j(){this.A.stop(0);this.v.disconnect();this.D.disconnect();this.A.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[1]=a;Y(this,this.D.detune,a,c,d);
break;case 3:this.m[2]=a;Y(this,this.D.Q,a,c,d);break;case 6:this.m[3]=a;Y(this,this.L.gain,a,c,d);break;case 7:this.m[4]=a,Y(this,this.A.frequency,a,c,d)}}};self.ee=class extends Z{constructor(b,a){super(b);this.T="gain";this.m=[a];this.l=X(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.cb.ld;switch(b){case 4:this.m[0]=e(a),Y(this,this.l.gain,e(a),c,d)}}};
self.he=class extends Z{constructor(b,a){super(b);this.T="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,Y(this,this.l.pan,a,c,d)}}};
self.ie=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.m=[a,c];this.l=X(this);this.l.gain.value=1-c/2;this.A=this.g.createOscillator();this.A.frequency.value=a;this.L=X(this);this.L.gain.value=c/2;this.A.connect(this.L);this.L.connect(this.l.gain);this.A.start(0)}j(){this.A.stop(0);this.A.disconnect();this.L.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;Y(this,this.l.gain,1-a/2,c,d);Y(this,this.L.gain,a/2,c,d);break;case 7:this.m[0]=a,Y(this,this.A.frequency,a,c,d)}}};
self.ge=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.m=[a,c];this.v=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.Bb=X(this);this.Bb.gain.value=0;this.A=this.g.createOscillator();this.A.frequency.value=a;this.A.connect(this.Bb.gain);this.A.start(0);this.v.connect(this.Bb);this.v.connect(this.h);this.Bb.connect(this.i)}j(){this.A.stop(0);this.A.disconnect();this.Bb.disconnect();this.v.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,Y(this,this.A.frequency,a,c,d)}}};
self.be=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.m=[a,c,d,e,f];this.v=X(this);this.ec=X(this);this.dc=X(this);b=d;.01>b&&(b=.01);this.ec.gain.value=b;this.dc.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.jc=this.g.createWaveShaper();this.Hc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Hc[32768+e]=f,this.Hc[32768-
e-1]=-f;this.jc.curve=this.Hc;this.v.connect(this.ec);this.v.connect(this.h);this.ec.connect(this.jc);this.jc.connect(this.dc);this.dc.connect(this.i)}j(){this.v.disconnect();this.ec.disconnect();this.jc.disconnect();this.dc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.Zd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.Yd=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Fd=new Float32Array(this.l.frequencyBinCount);this.Td=new Uint8Array(a);this.Rd=this.Xa=0;b=this.u;b.Oa.add(this);T(b)}j(){this.u.Oa.delete(this);this.l.disconnect();super.j()}Ea(){this.l.getFloatFrequencyData(this.Fd);this.l.getByteTimeDomainData(this.Td);const b=this.l.fftSize;let a=this.Xa=0;for(var c=0;c<b;++c){let d=(this.Td[c]-
128)/128;0>d&&(d=-d);this.Xa<d&&(this.Xa=d);a+=d*d}c=self.cb.te;this.Xa=c(this.Xa);this.Rd=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};"use strict";
self.Ca.La(class extends self.eb{constructor(b){super(b,"mouse");t(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.s.I.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{l(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{l(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
